# Site settings
title: A blog about Kevin Woo
description: A data science enthusiast
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "https://kevwoo.github.io/particle" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kevin Woo
user_description: quirky nerd
user_title: CS@Columbia University
email: dw2799@columbia.edu  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
