# Site settings
title: Welcome to Kevin's Blog!
description: A Data Science Enthusiast
# baseurl: "/kevwoo.github.io" # the subpath of your site, e.g. /blog
# url: "https://kevwoo.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kevin Woo
user_description:
user_title: Undergrad CS@Columbia University
email: dw2799@columbia.edu
github_username: kevwoo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
